// <auto-generated />
using System;
using IMS_CIS_Controller.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewMS.Migrations
{
    [DbContext(typeof(IMSDBContext))]
    [Migration("20231102091023_DependanciesAddedToInterviewTables")]
    partial class DependanciesAddedToInterviewTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.DmNameMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("DmName");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.GradeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.IEDStatusMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByAppUserId");

                    b.ToTable("IEDStatusMaster");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.LevelMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByAppUserId");

                    b.ToTable("LevelMaster");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.ModeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByAppUserId");

                    b.ToTable("ModeMaster");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.Recruiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Recruiter");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.RequirementTypeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("RequirementType");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.ResourceTypeMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("ResourceType");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.ResultMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByAppUserId");

                    b.ToTable("ResultMaster");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.RoleMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Source");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.UserMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ModifiedById")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.Additionalnformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Additional_Resources_Required_In_Future")
                        .HasColumnType("bit");

                    b.Property<int>("BasicDetailId")
                        .HasColumnType("int");

                    b.Property<string>("Client_Domain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Client_Geography")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name_Of_The_Client")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Project_Directly_With_Client_or_Through_Partner")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Project_Execution_Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Project_Revenue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("Project_Start_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tentative_Project_Duration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type_Of_Client")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type_Of_Project")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Visibility_of_Project")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BasicDetailId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("AdditionalInformation");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.Approval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApprovedByHr")
                        .HasColumnType("bit");

                    b.Property<bool>("ApprovedByPresident")
                        .HasColumnType("bit");

                    b.Property<int>("BasicDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitiatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BasicDetailId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Approval");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.BasicDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DmId")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("JobRequestNum")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameOfTheProject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NoOfVacancy")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequiredBy")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequirementType")
                        .HasColumnType("int");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DmId");

                    b.HasIndex("Grade");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("RequirementType");

                    b.HasIndex("ResourceType");

                    b.ToTable("BasicDetail");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.Candidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentCompany")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimarySkillSet")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.HRClientRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("IEDStatusId")
                        .HasColumnType("int");

                    b.Property<int>("InterviewCommonId")
                        .HasColumnType("int");

                    b.Property<string>("Interviewer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoiningOn")
                        .HasColumnType("datetime2");

                    b.Property<float>("MarksScoredInOnlineTest")
                        .HasColumnType("real");

                    b.Property<int>("ModeId")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForDecline")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReasonForEsspl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<string>("RoundName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkypeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("IEDStatusId");

                    b.HasIndex("InterviewCommonId");

                    b.HasIndex("ModeId");

                    b.HasIndex("ResultId");

                    b.ToTable("HRClientRound");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.InterviewCommon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CTCLPA")
                        .HasColumnType("real");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ContactNo")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ExpCTCLPA")
                        .HasColumnType("real");

                    b.Property<string>("JobOrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagementRoundId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoticePeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recruiter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RelevantExp")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("ManagementRoundId");

                    b.ToTable("InterviewCommon");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.JobSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasicDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KeySkill")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YOE")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasicDetailId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("JobSpecification");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.ManagementRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("InterviewCommonId")
                        .HasColumnType("int");

                    b.Property<string>("Interviewer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ModeId")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("InterviewCommonId");

                    b.HasIndex("ModeId");

                    b.HasIndex("ResultId");

                    b.ToTable("ManagementRound");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.Recruitment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CandidateID")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExpectedCTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameOfTheSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NoticePeriod")
                        .HasColumnType("int");

                    b.Property<int>("RecruiterID")
                        .HasColumnType("int");

                    b.Property<int>("RelevantExperience")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SourceID")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("RecruiterID");

                    b.HasIndex("SourceID");

                    b.HasIndex("StatusId");

                    b.ToTable("Recruitment");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.RequirementInDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasicDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasicDetailId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("RequirementInDetail");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.TechnicalRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("IEDStatusId")
                        .HasColumnType("int");

                    b.Property<int>("InterviewCommonId")
                        .HasColumnType("int");

                    b.Property<string>("Interviewer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("ModeId")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByAppUserId");

                    b.HasIndex("IEDStatusId");

                    b.HasIndex("InterviewCommonId");

                    b.HasIndex("LevelId");

                    b.HasIndex("ModeId");

                    b.HasIndex("ResultId");

                    b.ToTable("TechnicalRound");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.DmNameMaster", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.GradeMaster", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.IEDStatusMaster", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany("IEDStatusModified")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany("IEDStatusCreated")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("ModifiedByAppUser");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.LevelMaster", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany("LevelModified")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany("LevelMasterCreated")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("ModifiedByAppUser");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.ModeMaster", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany("ModeMasterModified")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany("ModeMasterCreated")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("ModifiedByAppUser");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.Recruiter", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany("RecruiterCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany("RecruiterModified")
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("ModifiedByAppUser");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.RequirementTypeMaster", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.ResourceTypeMaster", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.ResultMaster", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany("ResultMasterModified")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany("ResultMasterCreated")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("ModifiedByAppUser");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.Source", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany("SourceCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany("SourceModified")
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("ModifiedByAppUser");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.Status", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany("StatusCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany("StatusModified")
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("ModifiedByAppUser");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.UserMaster", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.RoleMaster", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.Additionalnformation", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.TransactionTables.BasicDetail", null)
                        .WithMany()
                        .HasForeignKey("BasicDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.Approval", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.TransactionTables.BasicDetail", null)
                        .WithMany()
                        .HasForeignKey("BasicDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.BasicDetail", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.DmNameMaster", null)
                        .WithMany()
                        .HasForeignKey("DmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.GradeMaster", null)
                        .WithMany()
                        .HasForeignKey("Grade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.RequirementTypeMaster", null)
                        .WithMany()
                        .HasForeignKey("RequirementType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.ResourceTypeMaster", null)
                        .WithMany()
                        .HasForeignKey("ResourceType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.Candidate", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany("CandidateCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany("CandidateModified")
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("ModifiedByAppUser");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.HRClientRound", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany("HRClientRoundModified")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany("HRClientRoundCreated")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.IEDStatusMaster", "IEDStatusMaster")
                        .WithMany()
                        .HasForeignKey("IEDStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.TransactionTables.InterviewCommon", "InterviewCommon")
                        .WithMany("HRClientRounds")
                        .HasForeignKey("InterviewCommonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.ModeMaster", "ModeMaster")
                        .WithMany()
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.ResultMaster", "ResultMaster")
                        .WithMany()
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("IEDStatusMaster");

                    b.Navigation("InterviewCommon");

                    b.Navigation("ModeMaster");

                    b.Navigation("ModifiedByAppUser");

                    b.Navigation("ResultMaster");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.InterviewCommon", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany("InterviewCommonModified")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany("InterviewCommonCreated")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.TransactionTables.ManagementRound", null)
                        .WithMany("interviewCommons")
                        .HasForeignKey("ManagementRoundId");

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("ModifiedByAppUser");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.JobSpecification", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.TransactionTables.BasicDetail", null)
                        .WithMany()
                        .HasForeignKey("BasicDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.ManagementRound", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany("ManagementRoundModified")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany("ManagementRoundCreated")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.TransactionTables.InterviewCommon", "InterviewCommon")
                        .WithMany("ManagementRounds")
                        .HasForeignKey("InterviewCommonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.ModeMaster", "ModeMaster")
                        .WithMany()
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.ResultMaster", "ResultMaster")
                        .WithMany()
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("InterviewCommon");

                    b.Navigation("ModeMaster");

                    b.Navigation("ModifiedByAppUser");

                    b.Navigation("ResultMaster");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.Recruitment", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.TransactionTables.Candidate", "candidate")
                        .WithMany("Recruitment")
                        .HasForeignKey("CandidateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.Recruiter", "recruiter")
                        .WithMany("Recruitment")
                        .HasForeignKey("RecruiterID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.Source", "source")
                        .WithMany("Recruitment")
                        .HasForeignKey("SourceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.Status", "Status")
                        .WithMany("Recruitment")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("ModifiedByAppUser");

                    b.Navigation("Status");

                    b.Navigation("candidate");

                    b.Navigation("recruiter");

                    b.Navigation("source");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.RequirementInDetail", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.TransactionTables.BasicDetail", null)
                        .WithMany()
                        .HasForeignKey("BasicDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", null)
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.TechnicalRound", b =>
                {
                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "ModifiedByAppUser")
                        .WithMany("TechnicalRoundModified")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.UserMaster", "CreatedByAppUser")
                        .WithMany("TechnicalRoundCreated")
                        .HasForeignKey("CreatedByAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.IEDStatusMaster", "IEDStatusMaster")
                        .WithMany()
                        .HasForeignKey("IEDStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.TransactionTables.InterviewCommon", "InterviewCommon")
                        .WithMany("TechnicalRounds")
                        .HasForeignKey("InterviewCommonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.LevelMaster", "LevelMaster")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.ModeMaster", "ModeMaster")
                        .WithMany()
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("IMS_CIS_Controller.Models.MasterTables.ResultMaster", "ResultMaster")
                        .WithMany()
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByAppUser");

                    b.Navigation("IEDStatusMaster");

                    b.Navigation("InterviewCommon");

                    b.Navigation("LevelMaster");

                    b.Navigation("ModeMaster");

                    b.Navigation("ModifiedByAppUser");

                    b.Navigation("ResultMaster");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.Recruiter", b =>
                {
                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.RoleMaster", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.Source", b =>
                {
                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.Status", b =>
                {
                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.MasterTables.UserMaster", b =>
                {
                    b.Navigation("CandidateCreated");

                    b.Navigation("CandidateModified");

                    b.Navigation("HRClientRoundCreated");

                    b.Navigation("HRClientRoundModified");

                    b.Navigation("IEDStatusCreated");

                    b.Navigation("IEDStatusModified");

                    b.Navigation("InterviewCommonCreated");

                    b.Navigation("InterviewCommonModified");

                    b.Navigation("LevelMasterCreated");

                    b.Navigation("LevelModified");

                    b.Navigation("ManagementRoundCreated");

                    b.Navigation("ManagementRoundModified");

                    b.Navigation("ModeMasterCreated");

                    b.Navigation("ModeMasterModified");

                    b.Navigation("RecruiterCreated");

                    b.Navigation("RecruiterModified");

                    b.Navigation("ResultMasterCreated");

                    b.Navigation("ResultMasterModified");

                    b.Navigation("SourceCreated");

                    b.Navigation("SourceModified");

                    b.Navigation("StatusCreated");

                    b.Navigation("StatusModified");

                    b.Navigation("TechnicalRoundCreated");

                    b.Navigation("TechnicalRoundModified");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.Candidate", b =>
                {
                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.InterviewCommon", b =>
                {
                    b.Navigation("HRClientRounds");

                    b.Navigation("ManagementRounds");

                    b.Navigation("TechnicalRounds");
                });

            modelBuilder.Entity("IMS_CIS_Controller.Models.TransactionTables.ManagementRound", b =>
                {
                    b.Navigation("interviewCommons");
                });
#pragma warning restore 612, 618
        }
    }
}
